[package]
name = "RsIceSettingsHost"
version = "0.1.0"

[app]
bundle_id = "dev.undivisible.rs-ice.settings"
deployment_target = "14.0"
sources = "macos/Sources"
resources = ["macos/views"]
embedded_dylibs = ["target/debug/libaurorality_core.dylib"]

[pre_build]
commands = [
    "true",
]
